"""add is_bookable to trip

Revision ID: 8140984a24e2
Revises: eb0e428fc6c6
Create Date: 2025-09-22 18:53:21.525632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8140984a24e2'
down_revision = 'eb0e428fc6c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_bookable', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.drop_column('is_bookable')

    # ### end Alembic commands ###
