"""add booking_mode to Trip

Revision ID: b1ebbbe1cb36
Revises: b1ebca866c90
Create Date: 2025-09-23 11:11:40.329410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1ebbbe1cb36'
down_revision = 'b1ebca866c90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_mode', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.drop_column('booking_mode')

    # ### end Alembic commands ###
