"""trip detail fields and TripPhoto

Revision ID: eb0e428fc6c6
Revises: cdf236a3b6e3
Create Date: 2025-09-22 18:19:04.307128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb0e428fc6c6'
down_revision = 'cdf236a3b6e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=512), nullable=False),
    sa.Column('caption', sa.String(length=300), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('short_description', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('detailed_plan', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('hero_image_url', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.drop_column('is_active')
        batch_op.drop_column('hero_image_url')
        batch_op.drop_column('detailed_plan')
        batch_op.drop_column('short_description')

    op.drop_table('trip_photo')
    # ### end Alembic commands ###
